In [1]:
import numpy as np
import os,glob
import pandas as pd

# CSV files to NPY files

## Step 1 :  change all csv files to npy files

In [2]:
path =glob.glob('lcs/*.csv')
#print(len(path))
dummy_i=1
c=[]
for x in path:
    data=np.genfromtxt(x,delimiter=',')
        
        #listing =df.convert_dtype('float64')
        #print(listing)
        #c.append(data)
    np.save('npy/'+str(dummy_i)+'.npy',data)
    dummy_i=dummy_i+1
    
print('the conversion is complete')

the conversion is complete


Check whether the files are equal or not

In [3]:
path =glob.glob('npy/*.npy')
print(len(path))

46411


# Change the npy files to a single npy file

In [4]:
path =glob.glob('npy/*.npy')
all_arrays =[]
path.sort()
for npfiles in path:
    all_arrays.append(np.load(npfiles).astype(np.float64))    
all_array =np.array(all_arrays)
np.save('lcs.npy',all_array)


/tmp/ipykernel_20114/2927616354.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  all_array =np.array(all_arrays)


Check the file by loading

In [5]:
lcs =np.load('lcs.npy',allow_pickle=True)
print(len(lcs))
print(lcs[100][0:5])

46411
[[5.82033773e+04 1.84048805e+01 3.86154652e-02]
 [5.82063446e+04 1.83142738e+01 3.62164453e-02]
 [5.82063656e+04 1.83537350e+01 3.72382440e-02]
 [5.82103880e+04 1.82501984e+01 3.46301571e-02]
 [5.82293366e+04 1.83590126e+01 3.73775586e-02]]


In [6]:
#path =glob.glob('lcs/*.csv')

#def data():
#    for x in path:
#        df =pd.read_csv(x,usecols=(0,1,2))
    #print(df)
    
#data =data()

lcs =np.load('lcs.npy',allow_pickle=True)

from tensorflow.keras.preprocessing.sequence import pad_sequences
lcs_raw = pad_sequences(lcs, value=np.nan, dtype='float', padding='post')
#functions taken from https://github.com/yutarotachibana/CatalinaQSO_AutoEncoder

def times_to_lags(T):
    """(N x n_step) matrix of times -> (N x n_step) matrix of lags.
    First time is assumed to be zero.
    """
    assert T.ndim == 2, "T must be an (N x n_step) matrix"
    return np.c_[np.diff(T, axis=1)/365., np.zeros(T.shape[0])]

def preprocess(X_raw, m_max=np.inf):
    X = X_raw.copy()
    #print(X)
    wrong_units =  np.all(np.isnan(X[:, :, 1])) | (np.nanmax(X[:, :, 1], axis=1) > m_max)
    #print(wrong_units)
    X = X[~wrong_units, :, :]
    X[:, :, 0] = times_to_lags(X[:, :, 0])
    #print(X[:, :, 0])
    means = np.atleast_2d(np.nanmean(X[:, :, 1], axis=1)).T
    #print(means)
    X[:, :, 1] -= means
    scales = np.atleast_2d(np.nanstd(X[:, :, 1], axis=1)).T
    #print(scales)
    X[:, :, 1] /= scales
    errors = X[:, :, 2] / scales
    #print(errors)
    X = X[:, :, :2]
    #print(X) is lcs_scaled value
    return X, means, scales, errors, wrong_units

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
#print(lcs_raw)
lcs_scaled, means,scales, errors, wrong_units =preprocess(lcs_raw)

In [ ]:
print(lcs_scaled[100][0:5])
print(means[100])
#print(lcs_scaled[1])

In [ ]:
path =glob.glob('lcs/*.csv')
print(len(path))
val =20
count=0
dummy_i=0
#def check(mag, val):
 #   return (all(x>= val for x in mag))
#print(check())
for i in path:
    df =pd.read_csv(i)
    df.columns =['mjd','mag','err']
    #if np.median(df['mag'])>=20:
    if len(df['mjd'])<=100:   
        new_file='less/'
        rename_file_cmd ='mv' + '  ' + path[count] + '  ' + new_file
        #rename_file_cmd ='mv' + '  ' + path2+  '  ' +path2+ new_file +'.csv'
        os.system(rename_file_cmd)
        count+=1
        #print('the data points are greater than 100')
    #dummy_i=dummy_i+1
    #print(df.head())if (check(df['mag'],val)):
    elif np.median(df['mag'])>=20:
      #  if j >=val:
        #print('magnitude is greater than or equal to 20'.format(count+1))
        #print(i)
        newer_file='median_above_20/'
        rename_file_cmd ='mv' + '  ' + path[count] + '  ' + newer_file
        os.system(rename_file_cmd)
        count+=1
    else: 
                newer_file='other/'
                rename_file_cmd ='mv' + '  ' + path[count] + '  ' + newer_file
                os.system(rename_file_cmd)
        
                count+=1
           # break
    #
     #   print(i)
        
        
     
print(count)
        

In [ ]:
path=glob.glob()

In [ ]:
path1=glob.glob('lcs/*.csv')
print(len(path1))
count=0
for i in path1:
    df = pd.read_csv(i)
    df.columns = ['mjd','mag','err']
    
    if df['mag']<20:
        count+=1

print(count)

In [9]:
import PyOrigin


ModuleNotFoundError: No module named 'PyOrigin'

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import glob,os
from keras.layers import Dense,GRU, Flatten, Conv2D, Dropout
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import (Callback, TensorBoard, EarlyStopping,
                             ModelCheckpoint, CSVLogger, ProgbarLogger)
from tensorflow.keras.layers import (Input, Dense, TimeDistributed, LSTM, GRU, Dropout, merge, 
                         Concatenate, Flatten, RepeatVector, Lambda, Bidirectional, SimpleRNN)
import sys
import csv
from collections import Iterable, OrderedDict
import datetime
from sklearn.manifold import TSNE
from tensorflow.keras.layers import Layer
from tensorflow.keras.layers import Conv2D, Conv2DTranspose, Input, Flatten, Dense, Lambda, Reshape
from tensorflow.keras.layers import SimpleRNN,Bidirectional,BatchNormalization
from tensorflow.keras.models import Model

from tensorflow.keras.losses import KLDivergence,binary_crossentropy
from tensorflow.keras import backend as K
from tensorflow.keras import layers
from tensorflow.keras.activations import relu, sigmoid
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import StandardScaler

In [ ]:
#shuffling the data to avoid systematics 
np.random.seed(42)
np.random.shuffle(lcs)
lcs[100][0:5]